In [9]:
import numpy as np

In [25]:
ps = [(-3, 3), (1, 4), (2, 6), (3, 8), (5, 2), (6, 11), (7, 1)]

In [41]:
arr = np.array(ps)
arr

array([[-3,  3],
       [ 1,  4],
       [ 2,  6],
       [ 3,  8],
       [ 5,  2],
       [ 6, 11],
       [ 7,  1]])

In [42]:
center = arr.mean(0)
center

array([ 3.,  5.])

In [43]:
diff = arr - center
diff

array([[-6., -2.],
       [-2., -1.],
       [-1.,  1.],
       [ 0.,  3.],
       [ 2., -3.],
       [ 3.,  6.],
       [ 4., -4.]])

In [44]:
diffsq = diff ** 2
diffsq

array([[ 36.,   4.],
       [  4.,   1.],
       [  1.,   1.],
       [  0.,   9.],
       [  4.,   9.],
       [  9.,  36.],
       [ 16.,  16.]])

In [49]:
ranges = np.sqrt(diffsq.sum(1))
ranges

array([ 6.32455532,  2.23606798,  1.41421356,  3.        ,  3.60555128,
        6.70820393,  5.65685425])

In [51]:
(ranges ** 2).sum()

146.0